config/routes.rb
Rails.application.routes.draw do
  resources :bike_points
  root "bike_points#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike_point.rb
class BikePoint < ApplicationRecord
  def self.search_address(address)
    point = GeolocationHelper::Geolocation.search_street(address)
    if point.nil?
      nil 
    else
      point 
    end
  end

  def self.get_nearest_points(point)
    points = BikePoint.all
    GeolocationHelper::Geolocation.get_nearest_points(point, points.to_a)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bike_points_controller.rb
class BikePointsController < ApplicationController
  before_action :set_bike_point, only: %i[ show edit update destroy ]

  # GET /bike_points or /bike_points.json
  def index
    @point = BikePoint.search_address(params[:search])
    if @point.empty? 
      @point = [-22.911091052609546, -43.205639965029214]
      if !params[:search].nil?
        flash[:notice] = "Local não encontrado"
      end
    end

    @bike_points = BikePoint.get_nearest_points(@point)
  end

  # GET /bike_points/1 or /bike_points/1.json
  def show
  end

  def search
  end

  # GET /bike_points/new
  def new
    @bike_point = BikePoint.new
  end

  # GET /bike_points/1/edit
  def edit
  end

  # POST /bike_points or /bike_points.json
  def create
    @bike_point = BikePoint.new(bike_point_params)

    respond_to do |format|
      if @bike_point.save
        format.html { redirect_to bike_point_url(@bike_point), notice: "Bike point was successfully created." }
        format.json { render :show, status: :created, location: @bike_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bike_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bike_points/1 or /bike_points/1.json
  def update
    respond_to do |format|
      if @bike_point.update(bike_point_params)
        format.html { redirect_to bike_point_url(@bike_point), notice: "Bike point was successfully updated." }
        format.json { render :show, status: :ok, location: @bike_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bike_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bike_points/1 or /bike_points/1.json
  def destroy
    @bike_point.destroy

    respond_to do |format|
      format.html { redirect_to bike_points_url, notice: "Bike point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike_point
      @bike_point = BikePoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bike_point_params
      params.require(:bike_point).permit(:district, :station, :code, :address, :number, :lat, :long, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_points_helper.rb
module BikePointsHelper
end

app/helpers/geolocation_helper.rb
module GeolocationHelper
  #https://www.geeksforgeeks.org/program-distance-two-points-earth/#:~:text=For%20this%20divide%20the%20values,is%20the%20radius%20of%20Earth.
  class Geolocation
    def self.search_street(address)
      # debugger

      client = OpenStreetMap::Client.new
      response = client.search(q: address, format: 'json', addressdetails: '1')
      if response.empty?
        response
      else 
        [response[0]['lat'].to_f, response[0]['lon'].to_f]
      end
    end

    def self.get_distance(pointA, pointB)
      lat1 = to_radian(pointA[0])
      long1 = to_radian(pointA[1])
      lat2 = to_radian(pointB[0])
      long2 = to_radian(pointB[1])

      dlong = long2 - long1
      dlat = lat2 - lat1

      a = Math.sin(dlat / 2)**2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dlong / 2)**2
      c = 2 * Math.asin(Math.sqrt(a))
      r = 6371
      c * r

    end

    def self.to_radian(point)
      point / (180/Math::PI)
    end

    def self.get_nearest_points(point, points)
      nearest = Array.new
      points.each do |array_point|
        array_point[:distance] = get_distance([to_radian(point[0]), to_radian(point[1])],
                          [to_radian(array_point[:lat]),to_radian(array_point[:long])])
      end
      points.sort_by{|point| [point.distance]}
    end
  end
end

app/views/bike_points/_bike_point.html.erb
<div class="accordion-item">
  <h2 class="accordion-header" id="heading<%= bike_point.code %>">
    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= bike_point.code %>" aria-expanded="true" aria-controls="collapse<%= bike_point.code %>">
      <%= bike_point.district %> - <%= bike_point.station %>
    </button>
  </h2>
  <div id="collapse<%= bike_point.code %>" class="accordion-collapse collapse" aria-labelledby="heading<%= bike_point.code %>">
    <div class="accordion-body">
      <strong>Endereço:</strong>
        <%= bike_point.address %> <%= bike_point.number.to_i %>
      </p>
      <div class="mapouter">
        <div class="gmap_canvas">
          <% src = "https://maps.google.com/maps?q=#{bike_point.lat},#{bike_point.long}&t=&z=15&ie=UTF8&iwloc=&output=embed" %>
      
          <iframe width="300" height="250" id="gmap_canvas" src="<%= src %>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
      
          </iframe>
          <br>
          <style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style>
          <style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style>
        </div>
      </div>
    
    </div>
  </div>
</div>
<!-- <div id="<%= dom_id bike_point %>">
  <p>
    <strong>District:</strong>
    <%= bike_point.district %>
  </p>

  <p>
    <strong>Station:</strong>
    <%= bike_point.station %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= bike_point.code %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= bike_point.address %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= bike_point.number %>
  </p> -->



  <!-- <p>
    <strong>Lat:</strong>
    <%= bike_point.lat %>
  </p>

  <p>
    <strong>Long:</strong>
    <%= bike_point.long %>
  </p> -->

  
<!-- </div> -->

app/views/bike_points/_form.html.erb
<%= form_with(model: bike_point) do |form| %>
  <% if bike_point.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bike_point.errors.count, "error") %> prohibited this bike_point from being saved:</h2>

      <ul>
        <% bike_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :district, style: "display: block" %>
    <%= form.text_field :district %>
  </div>

  <div>
    <%= form.label :station, style: "display: block" %>
    <%= form.text_field :station %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.number_field :code %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :lat, style: "display: block" %>
    <%= form.text_field :lat %>
  </div>

  <div>
    <%= form.label :long, style: "display: block" %>
    <%= form.text_field :long %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bike_points/_geolocation.html.erb
<div class="mapouter">
  <div class="gmap_canvas">
    <% src = "https://maps.google.com/maps?q=#{@point[0]},#{@point[1]}&t=&z=15&ie=UTF8&iwloc=&output=embed" %>

    <iframe width="300" height="250" id="gmap_canvas" src="<%= src %>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">

    </iframe>
    <br>
    
  </div>
</div>

app/views/bike_points/edit.html.erb
<h1>Editing bike point</h1>

<%= render "form", bike_point: @bike_point %>

<br>

<div>
  <%= link_to "Show this bike point", @bike_point %> |
  <%= link_to "Back to bike points", bike_points_path %>
</div>

app/views/bike_points/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="header">
  <h1>Bike points</h1>
  
  <p>Digite um endereço:</p>
  <div class="form-content">
    <%= form_tag(bike_points_path(@bike_point), method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Buscar") %>
    <% end %>
  </div>
</div>

<br>
<p>Seu endereço:</p>
<%= render "geolocation" %>

<br>
<p>Lista dos locais mais próximos:</p>
<!-- <div id="bike_points"> -->
<div class="accordion " id="accordionExample"></div>
  <% @bike_points.each do |bike_point| %>
    
    <%= render bike_point %>
    
  <% end %>
</div>

<%= link_to "New bike point", new_bike_point_path %>

app/views/bike_points/new.html.erb
<h1>New bike point</h1>

<%= render "form", bike_point: @bike_point %>

<br>

<div>
  <%= link_to "Back to bike points", bike_points_path %>
</div>

app/views/bike_points/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bike_point %>

<div>
  <%= link_to "Voltar para busca", bike_points_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocalizacao</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="content" >
      <%= yield %>
    </div>
  </body>
</html>